export const cartTypes={
    ADD_ITEM_IN_CART:   'ADD_ITEM_IN_CART',
    REMOVE_ITEM_IN_CART:   'REMOVE_ITEM_IN_CART',
    ADD_ORDER_IN_CART :'ADD_ORDER_IN_CART',
    PLACED_ORDER_IN_CART :'PLACED_ORDER_IN_CART',
        EMPTY_STATE_CART :' EMPTY_STATE_CART'
    
};