export const productTypes={
    ADD_PRODUCT:   'ADD_PRODUCT',
    UPDATE_PRODUCT:   'UPDATE_PRODUCT',
    DELETE_PRODUCT:   'DELETE_PRODUCT',
    ADD_LIGHTING:   'ADD_LIGHTING',
    UPDATE_LIGHTING:   'UPDATE_LIGHTING',
    DELETE_LIGHTING:   'DELETE_LIGHTING'
};